import './options.css';
import type { ImageFormat } from '../types/messages';
import { DEFAULT_SETTINGS, getSettings } from '../utils/settings';

const app = document.querySelector<HTMLElement>('#app')!;
app.innerHTML = `<section class="card"><div class="brand"><span><img src="../../icons/icon-48.png" alt=""></span><div><h1>SnapSave settings</h1><p>Simple defaults for every capture.</p></div></div><form><label>Default image format<select id="format"><option value="png">PNG</option><option value="jpeg">JPG</option></select></label><label>JPG quality<select id="quality">${[50,70,80,90,100].map(v => `<option value="${v/100}">${v}%</option>`).join('')}</select></label><label class="toggle"><span>Automatically download after capture<small>Skip the preview download step.</small></span><input id="auto" type="checkbox"></label><label class="toggle"><span>Include website name in filename<small>Example: snapsave-example-com-date.png</small></span><input id="website" type="checkbox"></label><div class="shortcuts"><strong>Keyboard shortcuts</strong><p>Chrome manages extension shortcuts. Open <code>chrome://extensions/shortcuts</code> to customize them.</p></div><button type="submit">Save settings</button><output aria-live="polite"></output></form></section>`;

const form = document.querySelector('form')!, format = document.querySelector<HTMLSelectElement>('#format')!, quality = document.querySelector<HTMLSelectElement>('#quality')!, auto = document.querySelector<HTMLInputElement>('#auto')!, website = document.querySelector<HTMLInputElement>('#website')!, output = document.querySelector<HTMLOutputElement>('output')!;
void getSettings().then(settings => { format.value = settings.format; quality.value = String(settings.jpgQuality); auto.checked = settings.autoDownload; website.checked = settings.includeWebsite; });
form.onsubmit = event => { event.preventDefault(); void chrome.storage.sync.set({ ...DEFAULT_SETTINGS, format: format.value as ImageFormat, jpgQuality: Number(quality.value), autoDownload: auto.checked, includeWebsite: website.checked }).then(() => { output.textContent = 'Settings saved'; setTimeout(() => output.textContent = '', 1800); }); };